[package]
name = "skryn"
version = "0.1"
authors = ["Fasih Rana <fasih.rana@apparicion.com>"]
exclude = [
	".idea",
	"Skryn.iml"
]

[dependencies]
winit = "^0.17"
glutin = "*"
webrender = {git = "https://github.com/servo/webrender"}
gleam = "*"
app_units = "0.6"
euclid = "0.18"
scan-rules = "*"
rusttype = "*"
font-loader = "*"
lazy_static = "*"

